# Generated by Django 3.1.5 on 2022-02-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('book_auother', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('book_publisher', models.CharField(blank=True, default='null', max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Book',
            },
        ),
    ]
