# Generated by Django 3.1.5 on 2022-02-05 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_auother',
            new_name='book_author',
        ),
    ]
